export const GET_CURRENT_PROFILE_SUCCESS = "GET_CURRENT_PROFILE_SUCCESS";
export const GET_CURRENT_PROFILE_FAIL = "GET_CURRENT_PROFILE_FAIL";
export const GET_CURRENT_PROFILE_LOADING = "GET_CURRENT_PROFILE_LOADING";

export const CREATE_PROFILE_LOADING = "GET_CURRENT_PROFILE_LOADING";
export const CREATE_PROFILE_SUCCESS = "GET_CURRENT_PROFILE_SUCCESS";
export const CREATE_PROFILE_FAIL = "GET_CURRENT_PROFILE_FAIL";

export const UPLOAD_PROFILE_IMAGE_SUCCESS = "UPLOAD_PROFILE_IMAGE_SUCCESS";
export const UPLOAD_PROFILE_IMAGE_FAIL = "UPLOAD_PROFILE_IMAGE_FAIL";
export const UPLOAD_PROFILE_IMAGE_LOADING = "UPLOAD_PROFILE_IMAGE_LOADING";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING";

export const CREATE_WORKER_PROFILE_LOADING = "CREATE_WORKER_PROFILE_LOADING";
export const CREATE_WORKER_PROFILE_SUCCESS = "CREATE_WORKER_PROFILE_SUCCESS";
export const CREATE_WORKER_PROFILE_FAIL = "CREATE_WORKER_PROFILE_FAIL";
